[package]
name = "solana_coinflip"
version = "0.1.0"
edition = "2021"

[lib]
name = "solana_coinflip"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
anchor-lang = "0.29.0"
